name: CI Pipeline
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout code from repository
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      # Step 2: Set up Java (change version if needed, e.g. 11 or 21)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build project with maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test
